platform :ios, '7.0'

pod 'AFNetworking',       '~> 2.4.1'
pod 'XCTAsyncTestCase',   '~> 0.1.0'
pod 'OHHTTPStubs',        '~> 3.1.5'

# Comment out this line if working on VideoCore
pod 'VideoCore',          '~> 0.1.10'

# Uncomment this line if working on VideoCore (also remove VideoCore version from cineio-ios.podspec)
#pod 'VideoCore',          path: '/Users/jeffrey/dev/cine-dev/VideoCore'
