platform :ios, '6.0'

pod 'AFNetworking',       '~> 2.2.4'
pod 'XCTAsyncTestCase',   '~> 0.1.0'
pod 'VideoCore',          '~> 0.1.8'
#pod 'VideoCore',          path: '/Users/jeffrey/dev/cine-dev/VideoCore'
