source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'AFNetworking',       '~> 2.5'
#pod 'XCTAsyncTestCase',   '~> 0.1.1'  # 0.1.1 hasn't been pushed to trunk yet. :-(
pod 'XCTAsyncTestCase', git: 'https://github.com/iheartradio/xctest-additions.git'
pod 'OHHTTPStubs',        '~> 4.0'

# Comment out this line if working on VideoCore
#pod 'VideoCore', :git => 'https://github.com/ArenaCloud/VideoCore.git', :branch => 'master'

# Comment out this line if working on ijkplayer
#pod 'ijkplayer', :git => 'https://github.com/ArenaCloud/ijkplayer.git', :tag => '1.1.0'

# Uncomment this line if working on VideoCore (also remove VideoCore version from cineio-ios.podspec)
pod 'VideoCore', :path => '../../VideoCore'

# Uncomment this line if working on ijkplayer
pod 'ijkplayer', :path => '../../ijkplayer'
